# Generated by Django 4.2.5 on 2023-10-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fromunit', models.CharField(max_length=100)),
                ('Tounit', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dis_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Notification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Dob', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Panchayath', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=100)),
                ('Village', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('ConnectionsStatus', models.CharField(max_length=100)),
                ('AREA', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Userupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Photo', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Year', models.CharField(max_length=100)),
                ('Month', models.CharField(max_length=100)),
                ('Usage', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('Payment_status', models.CharField(max_length=100)),
                ('Type', models.CharField(default='Monthly Bill', max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount', models.CharField(max_length=100)),
                ('REQUESTID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.usage')),
            ],
        ),
        migrations.CreateModel(
            name='Meterreader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Dob', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Complaint', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('FROM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('TO', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.meterreader')),
            ],
        ),
        migrations.CreateModel(
            name='Assign_meter_reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AREA', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('METRERREADER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.meterreader')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district'),
        ),
    ]
