# Generated by Django 4.2.5 on 2023-10-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='District',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Place',
        ),
    ]
