# Generated by Django 4.2.5 on 2023-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_district_remove_user_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='Fromunit',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='charges',
            name='Tounit',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usage',
            name='Usage',
            field=models.FloatField(max_length=100),
        ),
    ]
