# Generated by Django 4.2.5 on 2023-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accno', models.CharField(max_length=100)),
                ('Ifsc', models.CharField(max_length=100)),
                ('Balance', models.CharField(max_length=100)),
                ('Cvv', models.CharField(max_length=100)),
            ],
        ),
    ]
